import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#141b2b",
        "on-tertiary-fixed": "#1e1b14",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed": "#151c27",
        "surface-container": "#ebeef3",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#141b2b",
        "surface-tint": "#575e70",
        "surface-container-high": "#e5e8ed",
        "surface-bright": "#f7f9fe",
        "on-surface-variant": "#45464c",
        "tertiary-fixed-dim": "#cdc6ba",
        "on-secondary-container": "#5e6572",
        "secondary-fixed": "#dce2f3",
        "primary-fixed-dim": "#c0c6db",
        error: "#ba1a1a",
        outline: "#76777d",
        "inverse-surface": "#2d3135",
        "on-primary-fixed-variant": "#404758",
        surface: "#f7f9fe",
        "on-error-container": "#93000a",
        "surface-container-low": "#f1f4f9",
        primary: "#000000",
        "on-primary-container": "#7d8497",
        "surface-container-highest": "#dfe3e8",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eef1f6",
        "primary-fixed": "#dce2f7",
        "on-tertiary-fixed-variant": "#4a463d",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#e9e2d5",
        secondary: "#585f6c",
        "surface-dim": "#d7dadf",
        "on-background": "#181c20",
        background: "#f7f9fe",
        "on-surface": "#181c20",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#898378",
        "secondary-container": "#dce2f3",
        "inverse-primary": "#c0c6db",
        "tertiary-container": "#1e1b14",
        "surface-variant": "#dfe3e8",
        tertiary: "#000000",
        "secondary-fixed-dim": "#c0c7d6",
        "on-secondary-fixed-variant": "#404754",
        "cream-clay": "#FEF6E9",
        "mist-grey": "#F1F4F9",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
